name = "ambient-access-layer"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Custom domains
routes = [
  { pattern = "optimization-inversion.genesisconductor.io", custom_domain = true }
]

# KV Namespaces
[[kv_namespaces]]
binding = "API_KEYS"
id = "4c2c5ef0988742cc8fb98102681d9986"

# D1 Database
[[d1_databases]]
binding = "TASK_DB"
database_name = "ambient-db"
database_id = "56fc54e4-a04c-4f6d-b0af-048bdfa777d8"

# Static assets
[assets]
directory = "./public"
binding = "STATIC_ASSETS"
